version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_URL: "myapp-docker-registry-url"
    DOCKER_REGISTRY_USERNAME: "myapp-docker-registry-username"
    DOCKER_REGISTRY_PASSWORD: "myapp-docker-registry-password"
phases:
  install:
    runtime-versions:
      python: 3.11
      
  pre_build:
    commands:
      - echo "prebuild stage- Installing all the dependencies!"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "build stage- building the docker image!"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app-image:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app-image:latest"

  post_build:
    commands:
      - echo "Build was successfull"
  artifacts:
    files:
      - '**/*'
